import {
  faArrowLeft,
  faBars,
  faCheck,
  faCheckCircle,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faCircle,
  faEdit,
  faInfo,
  faPaperPlane,
  faPlus,
  faTimes,
  faTrash,
} from '@fortawesome/free-solid-svg-icons';

export const Icons = {
  CROSS: faTimes,
  EDIT: faEdit,
  NAV: faBars,
  DELETE: faTrash,
  INFOS: faInfo,
  CHECKED: faCheck,
  PLUS: faPlus,
  SEND: faPaperPlane,
  LEFT: faArrowLeft,
  CIRCLE: faCircle,
  CIRCLECHECKED: faCheckCircle,
  CHEVRONLEFT: faChevronLeft,
  CHEVRONRIGHT: faChevronRight,
  CHEVRONUP: faChevronUp,
  CHEVRONDOWN: faChevronDown,
};
